/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module spi_slave(clk, cs_n, mosi, miso, parallel_out);
  wire [2:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [2:0] bit_cnt;
  input clk;
  input cs_n;
  output miso;
  input mosi;
  output [3:0] parallel_out;
  wire [3:0] reg_control;
  wire [3:0] reg_status;
  wire [7:0] shift_reg;
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(cs_n),
    .Y(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(bit_cnt[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(reg_control[0]),
    .A1(reg_status[0]),
    .S(cs_n),
    .X(parallel_out[0])
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(reg_control[1]),
    .A1(reg_status[1]),
    .S(cs_n),
    .X(parallel_out[1])
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(reg_control[2]),
    .A1(reg_status[2]),
    .S(cs_n),
    .X(parallel_out[2])
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(reg_control[3]),
    .A1(reg_status[3]),
    .S(cs_n),
    .X(parallel_out[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _25_ (
    .A(shift_reg[7]),
    .SLEEP(cs_n),
    .X(miso)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[2]),
    .C(bit_cnt[0]),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor4_1 _27_ (
    .A(cs_n),
    .B(shift_reg[5]),
    .C(shift_reg[6]),
    .D(shift_reg[7]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3_1 _28_ (
    .A(shift_reg[4]),
    .B(_14_),
    .C(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(shift_reg[0]),
    .A1(reg_status[0]),
    .S(_16_),
    .X(_02_[0])
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(shift_reg[1]),
    .A1(reg_status[1]),
    .S(_16_),
    .X(_02_[1])
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(shift_reg[2]),
    .A1(reg_status[2]),
    .S(_16_),
    .X(_02_[2])
  );
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(shift_reg[3]),
    .A1(reg_status[3]),
    .S(_16_),
    .X(_02_[3])
  );
  sky130_fd_sc_hd__and3b_1 _33_ (
    .A_N(shift_reg[4]),
    .B(_14_),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(reg_control[0]),
    .A1(shift_reg[0]),
    .S(_17_),
    .X(_01_[0])
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(reg_control[1]),
    .A1(shift_reg[1]),
    .S(_17_),
    .X(_01_[1])
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(reg_control[2]),
    .A1(shift_reg[2]),
    .S(_17_),
    .X(_01_[2])
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(reg_control[3]),
    .A1(shift_reg[3]),
    .S(_17_),
    .X(_01_[3])
  );
  sky130_fd_sc_hd__xor2_1 _38_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _39_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[0]),
    .B1(bit_cnt[2]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(_14_),
    .B(_18_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__clkinv_1 _41_ (
    .A(cs_n),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _42_ (
    .A(cs_n),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(cs_n),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(cs_n),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(cs_n),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _46_ (
    .A(cs_n),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _47_ (
    .A(cs_n),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _48_ (
    .A(cs_n),
    .Y(_10_)
  );
  sky130_fd_sc_hd__clkinv_1 _49_ (
    .A(cs_n),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(cs_n),
    .Y(_12_)
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_01_[0]),
    .Q(reg_control[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_01_[1]),
    .Q(reg_control[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_01_[2]),
    .Q(reg_control[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_01_[3]),
    .Q(reg_control[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(reg_status[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_02_[1]),
    .Q(reg_status[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_02_[2]),
    .Q(reg_status[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(clk),
    .D(_02_[3]),
    .Q(reg_status[3])
  );
  sky130_fd_sc_hd__dfrtp_1 _59_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(bit_cnt[0]),
    .RESET_B(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _60_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(bit_cnt[1]),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_1 _61_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(bit_cnt[2]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _62_ (
    .CLK(clk),
    .D(mosi),
    .Q(shift_reg[0]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _63_ (
    .CLK(clk),
    .D(shift_reg[0]),
    .Q(shift_reg[1]),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _64_ (
    .CLK(clk),
    .D(shift_reg[1]),
    .Q(shift_reg[2]),
    .RESET_B(_08_)
  );
  sky130_fd_sc_hd__dfrtp_1 _65_ (
    .CLK(clk),
    .D(shift_reg[2]),
    .Q(shift_reg[3]),
    .RESET_B(_09_)
  );
  sky130_fd_sc_hd__dfrtp_1 _66_ (
    .CLK(clk),
    .D(shift_reg[3]),
    .Q(shift_reg[4]),
    .RESET_B(_10_)
  );
  sky130_fd_sc_hd__dfrtp_1 _67_ (
    .CLK(clk),
    .D(shift_reg[4]),
    .Q(shift_reg[5]),
    .RESET_B(_11_)
  );
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(clk),
    .D(shift_reg[5]),
    .Q(shift_reg[6]),
    .RESET_B(_12_)
  );
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(clk),
    .D(shift_reg[6]),
    .Q(shift_reg[7]),
    .RESET_B(_13_)
  );
endmodule
